name: example_experiment
task: ['DS-PR']
solver: all
benchmark: 17
timeout: 600
repetitions: 1
result_format: csv
plot: ['cactus']
statistics: ['mean','solved','timeouts','coverage']
archive: ['zip']
save_output: False
